---
#########################################
# 가상 호스트 생성
# 1) 패키지 설치 - httpd, mod_ssl, firewalld
# 2) 서비스 설정
# * /etc/httpd/conf.d/vhost.conf
#   => vhost.conf.j2 --> /etc/httpd/conf.d/vhost.conf
# * /var/www/vhosts/ansible1/index.html
#   => /var/www/vhosts
#   => index.html -> /var/www/vhosts/ansible1/index.html
# 3) 서비스 기동 - httpd, firewalld
# 4) 방화벽 등록 - http, https
#########################################
- name: 가상 호스트 설정 역할 playbook
  hosts: webservers
  gather_facts: true
  pre_tasks:
    - name: 사전 작업 메세지
      ansible.builtin.debug:
        msg: '웹 서버 구성 시작'

  tasks:
    - name: 가상 호스트 설정 역할
      ansible.builtin.include_role:
        name: myvhost
