---
- name: DB 설치 작업
  hosts: databases
  remote_user:
  vars:
    pkg_db:
      - mariadb-server
      - python3-PyMySQL
    svc_db: mariadb
    conf_get_url: 'http://control/my.cnf.standard'
    conf_mysql: '/etc/my.cnf'
  tasks:
    #########################################################
    # 1) DB 패키지 설치 - mariadb-server, python3-PyMySQL
    # + DB 암호 설정(root/soldesk1., ALL)
    # 2) DB 서비스 기동 - mariadb
    # 3) ansible: /var/www/html/my.cnf.standard --get_url --> /etc/my.cnf
    # + DB 서비스 재기동 
    #########################################################
    - name: 1) 설정 파일 삭제 - /etc/my.cnf
      ansible.builtin.file:
        path: /etc/my.cnf
        state: absent

    - name: 2) DB 서비스 중지
      ansible.builtin.systemd:
        name: "{{ svc_db }}"
        state: stopped
        enabled: false

    - name: 3) DB 패키지 삭제
      ansible.builtin.dnf:
        name: "{{ pkg_db }}"
        state: absent
