---
- name: Restore_intranet.yml
  hosts: all
  tasks:
    - name: 1) 방화벽 제거 - http
      ansible.posix.firewalld:
        service: http
        permanent: true
        immediate: true
        state: disabled
      # ignore_errors: true

    - name: 2) 웹 서비스 중지 - (systemd) httpd.service
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
        enabled: false
      loop:
        - httpd
        - firewalld

    - name: 3) 파일 삭제 - /var/www/html/index.html
      ansible.builtin.file:
        path: /var/www/html/index.html
        state: absent

    - name: 4) 패키지 삭제 - httpd
      ansible.builtin.yum:
        name: httpd
        state: absent
