---
########################################
# Play1: 웹 서버 설정
# * 1) 패키지 설치 - httpd, mod_ssl, firewalld, python3-PyMySQL
# * 2) WEB 서비스 설정 - /var/www/html/index.html
# * 3) WEB 서비스 기동 - httpd, firewalld
# * 4) 방화벽 등록 - http, https
# Play2: 웹 서버 테스트
# * 1) 웹 요청 - http://192.168.10.10
# * 2) 웹 출력 확인
########################################
# Play1: 웹 서버 설정
- name: Play1 웹 서버 설정
  hosts: webserver
  vars:
    pkg_http_web: httpd
    pkg_https_web: mod_ssl
    pkg_fw: firewalld
    pkg_python: python3-PyMySQL
    basedir: /var/www/html
    indexfile: "{{ basedir }}/index.html"
    svc_web: httpd
    svc_fw: firewalld
    fw_var1: http
    fw_var2: https
  tasks:
    - name: 1) 패키지 설치 - {{ pkg_http_web }}, {{ pkg_https_web }}, ...
      ansible.builtin.dnf:
        name:
          - "{{ pkg_http_web }}"
          - "{{ pkg_https_web }}"
          - "{{ pkg_fw }}"
          - "{{ pkg_python }}"
        state: present

    - name: 2) WEB 서비스 설정 - {{ indexfile }}
      ansible.builtin.copy:
        content: |
          'Test Web Page\n'
        dest: "{{ indexfile }}"
        mode: '0644'

    - name: 3) 서비스 기동 - {{ svc_web }}, {{ svc_fw }}
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - "{{ svc_web }}"
        - "{{ svc_fw }}"

    - name: 4) 방화벽 등록 - {{ fw_var1 }}, {{ fw_var2 }}
      ansible.posix.firewalld:
        service: "{{ item }}"
        permanent: true
        immediate: true
        state: enabled
      loop:
        - "{{ fw_var1 }}"
        - "{{ fw_var2 }}"

- name: Play2 - 웹 서버 테스트
  hosts: all
  vars:
    url: "http://192.168.10.11/"
  tasks:
    - name: 1) 웹 요청 - http://192.168.10.11
      ansible.builtin.uri:
        url: "{{ url }}index.html"
        return_content: true
        status_code: 200
      register: output

    - name: 2) 웹 출력 확인
      ansible.builtin.debug:
        var:
          - output.server
          - output.url
          - output.last_modified
