---
- name: Play 01 - DB 서비스 기동
  hosts: all
  gather_facts: false
  vars:
    mariadb_packages:
      - mariadb-server
      - python3-PyMySQL
      - mariadb
    db_svc: mariadb
  tasks:
  ##################################
  # 1) 패키지 설치 - mariadb, mariadb-server, python3-PyMySQL
  # 2) 서비스 기동 - mariadb
  ##################################
    - name: 2) 서비스 기동
      ansible.builtin.systemd:
        name: "{{ db_svc }}"
        state: stopped
        enabled: false

    - name: 1) 패키지 설치
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: absent
      loop: "{{ mariadb_packages }}"
      #when: ansible_distribution == "CentOS"